/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import ModeloBeans.BeansCarros;
import ModeloConection.ConectaDB;
import ModeloDao.DaoCarros;
import ModeloDao.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Bruno
 */
public class formCarros extends javax.swing.JFrame {
BeansCarros func = new BeansCarros();
 DaoCarros control = new DaoCarros();
 ConectaDB conecta= new ConectaDB();
    int flag=0;
    public formCarros() {
        initComponents();
        preencherTabela("select * from carros order by cod_carro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MatriculaCarro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NomeCarro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        modeloVeiculos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RenavamVeiculos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PlacaVeiculos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ChassiVeiculos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AnoVeiculos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CorVeiculos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ValorFIPEVeiculos = new javax.swing.JTextField();
        CAMPOPESQUISA = new javax.swing.JTextField();
        BOTAOPESQUISA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCadastroCarros = new javax.swing.JTable();
        BOTAONOVO = new javax.swing.JButton();
        cadastrarBtn = new javax.swing.JButton();
        BOTAOEXCLUIR = new javax.swing.JButton();
        BOTAOEDITAR = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSAIR = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("ID:");

        MatriculaCarro.setEnabled(false);

        jLabel2.setText("Nome Carro:");

        NomeCarro.setEnabled(false);
        NomeCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCarroActionPerformed(evt);
            }
        });

        jLabel3.setText("modelo:");

        modeloVeiculos.setEnabled(false);

        jLabel4.setText("Renavam:");

        RenavamVeiculos.setEnabled(false);

        jLabel5.setText("Placa:");

        PlacaVeiculos.setEnabled(false);

        jLabel6.setText("Chassi:");

        ChassiVeiculos.setEnabled(false);

        jLabel7.setText("Ano:");

        AnoVeiculos.setEnabled(false);

        jLabel8.setText("Cor:");

        CorVeiculos.setEnabled(false);

        jLabel9.setText("Valor Carro:");

        ValorFIPEVeiculos.setEnabled(false);

        BOTAOPESQUISA.setText("PESQUISA");
        BOTAOPESQUISA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOPESQUISAActionPerformed(evt);
            }
        });

        TabelaCadastroCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaCadastroCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCadastroCarrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaCadastroCarros);

        BOTAONOVO.setText("NOVO");
        BOTAONOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAONOVOActionPerformed(evt);
            }
        });

        cadastrarBtn.setText("SALVAR");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        BOTAOEXCLUIR.setText("EXCLUIR");
        BOTAOEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOEXCLUIRActionPerformed(evt);
            }
        });

        BOTAOEDITAR.setText("EDITAR");
        BOTAOEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOEDITARActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSAIR.setText("SAIR");
        jButtonSAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CAMPOPESQUISA, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(BOTAOPESQUISA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MatriculaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeCarro)
                            .addComponent(modeloVeiculos)
                            .addComponent(RenavamVeiculos)
                            .addComponent(PlacaVeiculos)
                            .addComponent(ChassiVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AnoVeiculos)
                                    .addComponent(CorVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ValorFIPEVeiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BOTAOEDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addComponent(jButtonSAIR))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cadastrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BOTAOEXCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(BOTAONOVO, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(2, 2, 2))))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MatriculaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NomeCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(AnoVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(modeloVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CorVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RenavamVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ValorFIPEVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PlacaVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ChassiVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CAMPOPESQUISA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTAOPESQUISA))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BOTAONOVO)
                        .addGap(18, 18, 18)
                        .addComponent(cadastrarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BOTAOEXCLUIR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BOTAOEDITAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSAIR)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Cadastro Carro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(879, 907));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NomeCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCarroActionPerformed

    private void BOTAONOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAONOVOActionPerformed
       flag = 1 ;
        NomeCarro.setEnabled(true);
        modeloVeiculos.setEnabled(true);
        RenavamVeiculos.setEnabled(true);
        PlacaVeiculos.setEnabled(true);
        ChassiVeiculos.setEnabled(true);
        AnoVeiculos.setEnabled(true);
        CorVeiculos.setEnabled(true);
        ValorFIPEVeiculos.setEnabled(true);
        cadastrarBtn.setEnabled(true);
        jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_BOTAONOVOActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
       if (flag==1){
           func.setNomeCarro(NomeCarro.getText());
           func.setModeloVeiculos(modeloVeiculos.getText());
           func.setRenavamVeiculos(Integer.parseInt(RenavamVeiculos.getText()));
           func.setPlacaVeiculos(Integer.parseInt(PlacaVeiculos.getText()));
           func.setChassiVeiculos(Integer.parseInt(ChassiVeiculos.getText()));
           func.setAnoVeiculos(Integer.parseInt(AnoVeiculos.getText()));
           func.setCorVeiculos(ValorFIPEVeiculos.getText());       
           func.setValorFIPEVeiculos(Integer.parseInt(ValorFIPEVeiculos.getText()));
           control.Cadastra(func);
           NomeCarro.setText("");
           PlacaVeiculos.setText("");
           modeloVeiculos.setText("");
           ChassiVeiculos.setText("");
    
           CorVeiculos.setText("");
           RenavamVeiculos.setText("");
           ValorFIPEVeiculos.setText("");
           AnoVeiculos.setText("");
           NomeCarro.setEnabled(false);
           PlacaVeiculos.setEnabled(false);
           MatriculaCarro.setEnabled(false);
           modeloVeiculos.setEnabled(false);
           ChassiVeiculos.setEnabled(false);
           CorVeiculos.setEnabled(false);
           RenavamVeiculos.setEnabled(false);
           ValorFIPEVeiculos.setEnabled(false);
           AnoVeiculos.setEnabled(false);
           cadastrarBtn.setEnabled(false);
       preencherTabela("select * from usuario order by usu_nome");   

    }
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    private void BOTAOEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOEXCLUIRActionPerformed
           int resposta= 0;
        resposta =JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir?");
        if(resposta ==JOptionPane.YES_OPTION){
            func.setMatriculaCarro(Integer.parseInt(MatriculaCarro.getText()));
            control.Excluir(func);
            MatriculaCarro.setText("");
            NomeCarro.setText("");
           PlacaVeiculos.setText("");
           modeloVeiculos.setText("");
           ChassiVeiculos.setText("");
    
           CorVeiculos.setText("");
           RenavamVeiculos.setText("");
           ValorFIPEVeiculos.setText("");
           AnoVeiculos.setText("");
            NomeCarro.setEnabled(false);
           PlacaVeiculos.setEnabled(false);
           MatriculaCarro.setEnabled(false);
           modeloVeiculos.setEnabled(false);
           ChassiVeiculos.setEnabled(false);
           CorVeiculos.setEnabled(false);
           RenavamVeiculos.setEnabled(false);
           ValorFIPEVeiculos.setEnabled(false);
           AnoVeiculos.setEnabled(false);
           cadastrarBtn.setEnabled(false);
           BOTAOEDITAR.setEnabled(false);
 preencherTabela("select * from carros order by nome_carro");

        }
    }//GEN-LAST:event_BOTAOEXCLUIRActionPerformed

    private void BOTAOEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOEDITARActionPerformed
       
flag=2;  
        NomeCarro.setEnabled(true);
        modeloVeiculos.setEnabled(true);
        RenavamVeiculos.setEnabled(true);
        PlacaVeiculos.setEnabled(true);
        ChassiVeiculos.setEnabled(true);
        AnoVeiculos.setEnabled(true);
        CorVeiculos.setEnabled(true);
        
        ValorFIPEVeiculos.setEnabled(true);
        cadastrarBtn.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        BOTAOEDITAR.setEnabled(false);
        BOTAONOVO.setEnabled(false);
        BOTAOEXCLUIR.setEnabled(false);
    }//GEN-LAST:event_BOTAOEDITARActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
      NomeCarro.setEnabled(!true);
        modeloVeiculos.setEnabled(!true);
        RenavamVeiculos.setEnabled(!true);
        PlacaVeiculos.setEnabled(!true);
        ChassiVeiculos.setEnabled(!true);
        AnoVeiculos.setEnabled(!true);
        CorVeiculos.setEnabled(!true);
        
        ValorFIPEVeiculos.setEnabled(!true);
        cadastrarBtn.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        BOTAONOVO.setEnabled(true);
        BOTAOEDITAR.setEnabled(false);
        BOTAOEXCLUIR.setEnabled(false);
        
        MatriculaCarro.setText("");
            NomeCarro.setText("");
           PlacaVeiculos.setText("");
           modeloVeiculos.setText("");
           ChassiVeiculos.setText("");
    
           CorVeiculos.setText("");
           RenavamVeiculos.setText("");
           ValorFIPEVeiculos.setText("");
           AnoVeiculos.setText("");

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAIRActionPerformed
          this.dispose();
    }//GEN-LAST:event_jButtonSAIRActionPerformed

    private void TabelaCadastroCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCadastroCarrosMouseClicked
        
 String nome_carro= ""+TabelaCadastroCarros.getValueAt(TabelaCadastroCarros.getSelectedRow(),1);
       conecta.Conexao();
       conecta.executaSql("select * from carros where nome_carro='"+nome_carro+"'");
     try {
         conecta.rs.first();
         MatriculaCarro.setText(String.valueOf(conecta.rs.getInt("cod_carro")));
         NomeCarro.setText(conecta.rs.getString("nome_carro"));
         modeloVeiculos.setText(conecta.rs.getString("modelo_carro"));
         RenavamVeiculos.setText(String.valueOf(conecta.rs.getInt("renavam_carro")));
         PlacaVeiculos.setText(String.valueOf(conecta.rs.getInt("placa_carro")));
         ChassiVeiculos.setText(conecta.rs.getString("chassi_carro"));
         AnoVeiculos.setText(String.valueOf(conecta.rs.getInt("ano_carro")));
        CorVeiculos.setText(String.valueOf(conecta.rs.getInt("cor_carro")));
        ValorFIPEVeiculos.setText(String.valueOf(conecta.rs.getInt("valor_carro")));

         
     } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane,"Erro ao Selecionar os dados"+ex);     }
       conecta.desconecta();
       BOTAOEDITAR.setEnabled(true);
       BOTAOEXCLUIR.setEnabled(true);
    }//GEN-LAST:event_TabelaCadastroCarrosMouseClicked

    private void BOTAOPESQUISAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOPESQUISAActionPerformed
       func.setPesquisaCarros(CAMPOPESQUISA.getText());
    BeansCarros model= control.buscaCarros(func);
     MatriculaCarro.setText(String.valueOf(model.getMatriculaCarro()));
    NomeCarro.setText(model.getNomeCarro());
    modeloVeiculos.setText(model.getModeloVeiculos());
    RenavamVeiculos.setText(String.valueOf(model.getRenavamVeiculos()));
    PlacaVeiculos.setText(String.valueOf(model.getPlacaVeiculos()));
    ChassiVeiculos.setText(String.valueOf(model.getChassiVeiculos()));
    AnoVeiculos.setText(String.valueOf(model.getAnoVeiculos()));
    CorVeiculos.setText(String.valueOf(model.getCorVeiculos()));
    ValorFIPEVeiculos.setText(String.valueOf(model.getValorFIPEVeiculos()));

    BOTAONOVO.setEnabled(false);
              MatriculaCarro.setText("");
             NomeCarro.setText("");
           PlacaVeiculos.setText("");
           modeloVeiculos.setText("");
           ChassiVeiculos.setText("");
    
           CorVeiculos.setText("");
           RenavamVeiculos.setText("");
           ValorFIPEVeiculos.setText("");
           AnoVeiculos.setText("");
    preencherTabela("select * from carros where nome_carro like'%"+func.getPesquisaCarros()+"%'");
    }//GEN-LAST:event_BOTAOPESQUISAActionPerformed

 public void preencherTabela(String sql){
       ArrayList dados  = new ArrayList();
       String [] colunas = new String[]{"ID","nome","modelo","renavam","placa","chassi","ano","cor","valor"};
       conecta.Conexao();
       conecta.executaSql(sql);
       
       
       try{
           conecta.rs.first();
           do{
               dados.add(new Object[]{conecta.rs.getString("cod_carro"),conecta.rs.getString("nome_carro"),conecta.rs.getString("modelo_carro"),
                   conecta.rs.getString("renavam_carro"),conecta.rs.getString("placa_carro"),
                   conecta.rs.getString("chassi_carro"),conecta.rs.getString("ano_carro"),conecta.rs.getString("cor_carro"),conecta.rs.getString("valor_carro")});
           }while(conecta.rs.next());
           
       }catch (SQLException ex){
          // JOptionPane.showMessageDialog(rootPane,"Erro ao Preencher ArrayList"+ex);
           
       }
       ModeloTabela modelo = new ModeloTabela(dados,colunas);
       TabelaCadastroCarros.setModel(modelo);
       TabelaCadastroCarros.getColumnModel().getColumn(0).setPreferredWidth(35);
       TabelaCadastroCarros.getColumnModel().getColumn(0).setResizable(false);
       TabelaCadastroCarros.getColumnModel().getColumn(1).setPreferredWidth(180);
       TabelaCadastroCarros.getColumnModel().getColumn(1).setResizable(false);
       TabelaCadastroCarros.getColumnModel().getColumn(2).setPreferredWidth(80);
       TabelaCadastroCarros.getColumnModel().getColumn(2).setResizable(false);
       TabelaCadastroCarros.getColumnModel().getColumn(3).setPreferredWidth(80);
       TabelaCadastroCarros.getColumnModel().getColumn(3).setResizable(false);
       TabelaCadastroCarros.getColumnModel().getColumn(4).setPreferredWidth(80);
       TabelaCadastroCarros.getColumnModel().getColumn(4).setResizable(false);
       TabelaCadastroCarros.getColumnModel().getColumn(5).setPreferredWidth(80);
       TabelaCadastroCarros.getColumnModel().getColumn(5).setResizable(false);
       TabelaCadastroCarros.getColumnModel().getColumn(6).setPreferredWidth(80);
       TabelaCadastroCarros.getColumnModel().getColumn(6).setResizable(false);
       TabelaCadastroCarros.getColumnModel().getColumn(7).setPreferredWidth(80);
       TabelaCadastroCarros.getColumnModel().getColumn(7).setResizable(false);
       TabelaCadastroCarros.getColumnModel().getColumn(8).setPreferredWidth(80);
       TabelaCadastroCarros.getColumnModel().getColumn(8).setResizable(false);
       
       TabelaCadastroCarros.getTableHeader().setReorderingAllowed(false);
       TabelaCadastroCarros.setAutoResizeMode(TabelaCadastroCarros.AUTO_RESIZE_OFF);
       TabelaCadastroCarros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
       conecta.desconecta();
 }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnoVeiculos;
    private javax.swing.JButton BOTAOEDITAR;
    private javax.swing.JButton BOTAOEXCLUIR;
    private javax.swing.JButton BOTAONOVO;
    private javax.swing.JButton BOTAOPESQUISA;
    private javax.swing.JTextField CAMPOPESQUISA;
    private javax.swing.JTextField ChassiVeiculos;
    private javax.swing.JTextField CorVeiculos;
    private javax.swing.JTextField MatriculaCarro;
    private javax.swing.JTextField NomeCarro;
    private javax.swing.JTextField PlacaVeiculos;
    private javax.swing.JTextField RenavamVeiculos;
    private javax.swing.JTable TabelaCadastroCarros;
    private javax.swing.JTextField ValorFIPEVeiculos;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSAIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField modeloVeiculos;
    // End of variables declaration//GEN-END:variables
}
