/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import ModeloBeans.BeansUsuario;
import ModeloConection.ConectaDB;
import ModeloDao.DaoUsuario;
import ModeloDao.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Bruno
 */
public class FormUser extends javax.swing.JFrame {

   BeansUsuario func = new BeansUsuario();
 DaoUsuario control = new DaoUsuario();
 ConectaDB conecta= new ConectaDB();
  int flag=0;
    public FormUser() {
        initComponents();
                preencherTabela("select * from usuario order by usu_nome");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codFunc = new javax.swing.JLabel();
        IDcodigo = new javax.swing.JTextField();
        NOMEFUNC = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCargo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldRG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TELEFONE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CELULAR = new javax.swing.JTextField();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonPESQUISA = new javax.swing.JButton();
        jButtonNOVO = new javax.swing.JButton();
        jButtonEDITAR = new javax.swing.JButton();
        jButtonEXCLUIR = new javax.swing.JButton();
        jButtonSALVAR = new javax.swing.JButton();
        jButtonSAIR = new javax.swing.JButton();
        jButtonCANCELAR = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSexo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ENDUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        NumeroUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CEPUsuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CidadeUsuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        BairroUsuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        DATANASCIUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        SalarioUsuario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        codFunc.setText("ID:");

        IDcodigo.setEnabled(false);

        NOMEFUNC.setText("Nome:");

        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Profisssao:");

        jTextFieldCargo.setEnabled(false);
        jTextFieldCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCargoActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF:");

        jTextFieldCPF.setEnabled(false);

        jLabel3.setText("RG:");

        jTextFieldRG.setEnabled(false);

        jLabel4.setText("TEL:");

        TELEFONE.setEnabled(false);

        jLabel5.setText("CEL:");

        CELULAR.setEnabled(false);

        jTextFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaActionPerformed(evt);
            }
        });

        jButtonPESQUISA.setText("PESQUISA");
        jButtonPESQUISA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPESQUISAActionPerformed(evt);
            }
        });

        jButtonNOVO.setText("NOVO");
        jButtonNOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNOVOActionPerformed(evt);
            }
        });

        jButtonEDITAR.setText("EDITAR");
        jButtonEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEDITARActionPerformed(evt);
            }
        });

        jButtonEXCLUIR.setText("EXCLUIR");
        jButtonEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEXCLUIRActionPerformed(evt);
            }
        });

        jButtonSALVAR.setText("SALVAR");
        jButtonSALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSALVARActionPerformed(evt);
            }
        });

        jButtonSAIR.setText("SAIR");
        jButtonSAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAIRActionPerformed(evt);
            }
        });

        jButtonCANCELAR.setText("CANCELAR");
        jButtonCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCANCELARActionPerformed(evt);
            }
        });

        jLabel9.setText("sexo:");

        jTextFieldSexo.setEnabled(false);

        jLabel10.setText("END:");

        ENDUsuario.setEnabled(false);

        jLabel6.setText("N°");

        NumeroUsuario.setEnabled(false);

        jLabel7.setText("CEP:");

        CEPUsuario.setEnabled(false);

        jLabel11.setText("CIDADE:");

        CidadeUsuario.setEnabled(false);

        jLabel12.setText("BAIRRO:");

        BairroUsuario.setEnabled(false);

        jLabel13.setText("NASC:");

        DATANASCIUsuario.setEnabled(false);

        jLabel14.setText("SALARIO:");

        SalarioUsuario.setEnabled(false);

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUsuario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(CELULAR))
                                            .addComponent(jTextFieldRG)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(129, 129, 129)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonCANCELAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonSALVAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonPESQUISA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonNOVO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonEDITAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonEXCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonSAIR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addGap(28, 28, 28)
                                        .addComponent(BairroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(ENDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(codFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IDcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NOMEFUNC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DATANASCIUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SalarioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NumeroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CEPUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(370, 370, 370))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NOMEFUNC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CELULAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(NumeroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CEPUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ENDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CidadeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(BairroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(DATANASCIUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(SalarioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonPESQUISA)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonNOVO)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEDITAR)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEXCLUIR)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSALVAR)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCANCELAR)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSAIR))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );

        jLabel8.setText("CADASTRO USUARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );

        setSize(new java.awt.Dimension(923, 896));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCargoActionPerformed

    private void jButtonEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEXCLUIRActionPerformed
            int resposta= 0;
        resposta =JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir?");
        if(resposta ==JOptionPane.YES_OPTION){
            func.setUsuCod(Integer.parseInt(IDcodigo.getText()));
            control.Excluir(func);
           jTextFieldNome.setText("");
          IDcodigo.setText("");
       jTextFieldNome.setText("");
           jTextFieldCargo.setText("");
           jTextFieldRG.setText("");
           jTextFieldSexo.setText("");
           jTextFieldCPF.setText("");
           CELULAR.setText("");
           TELEFONE.setText("");
           ENDUsuario.setText("");
           NumeroUsuario.setText("");
           CEPUsuario.setText("");
           CidadeUsuario.setText("");
           BairroUsuario.setText("");
           DATANASCIUsuario.setText("");
           SalarioUsuario.setText("");
            jTextFieldNome.setEnabled(false);
        jTextFieldCargo.setEnabled(false);
        jTextFieldCPF.setEnabled(false);
        jTextFieldRG.setEnabled(false);
        jTextFieldSexo.setEnabled(false);
        TELEFONE.setEnabled(false);
        CELULAR.setEnabled(false);
        ENDUsuario.setEnabled(false);
           NumeroUsuario.setEnabled(false);
           CEPUsuario.setEnabled(false);
           CidadeUsuario.setEnabled(false);
           BairroUsuario.setEnabled(false);
           DATANASCIUsuario.setEnabled(false);
           SalarioUsuario.setEnabled(false);
      
        jButtonSALVAR.setEnabled(false);
           jButtonEDITAR.setEnabled(false);
 preencherTabela("select * from usuario order by usu_nome");
    }//GEN-LAST:event_jButtonEXCLUIRActionPerformed
    }
    private void jButtonNOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNOVOActionPerformed
        flag = 1 ; 
        jTextFieldNome.setEnabled(true);
        jTextFieldCargo.setEnabled(true);
        jTextFieldCPF.setEnabled(true);
        jTextFieldRG.setEnabled(true);
        jTextFieldSexo.setEnabled(true);
        TELEFONE.setEnabled(true);
        CELULAR.setEnabled(true);
        ENDUsuario.setEnabled(true);
           NumeroUsuario.setEnabled(true);
           CEPUsuario.setEnabled(true);
           CidadeUsuario.setEnabled(true);
           BairroUsuario.setEnabled(true);
           DATANASCIUsuario.setEnabled(true);
           SalarioUsuario.setEnabled(true);
      
        jButtonSALVAR.setEnabled(true);
        jButtonCANCELAR.setEnabled(true);
          jTextFieldNome.setText("");
          IDcodigo.setText("");
       jTextFieldNome.setText("");
           jTextFieldCargo.setText("");
           jTextFieldRG.setText("");
           jTextFieldSexo.setText("");
           jTextFieldCPF.setText("");
           CELULAR.setText("");
           TELEFONE.setText("");
           ENDUsuario.setText("");
           NumeroUsuario.setText("");
           CEPUsuario.setText("");
           CidadeUsuario.setText("");
           BairroUsuario.setText("");
           DATANASCIUsuario.setText("");
           SalarioUsuario.setText("");
      
        jButtonEDITAR.setEnabled(false);
        jButtonEXCLUIR.setEnabled(false);
        jButtonPESQUISA.setEnabled(false);
        jTextFieldPesquisa.setEnabled(false);
    }//GEN-LAST:event_jButtonNOVOActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaActionPerformed

    private void jButtonSALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSALVARActionPerformed
           if (flag==1){
           func.setUsuNome(jTextFieldNome.getText());
           func.setUsuProfissao(jTextFieldCargo.getText());
           func.setUsuRg(Integer.parseInt(jTextFieldRG.getText()));
           func.setUsuSexo(jTextFieldSexo.getText());
           func.setUsuCpf(Integer.parseInt(jTextFieldCPF.getText()));
           func.setUsuCel(Integer.parseInt(CELULAR.getText()));
           func.setUsuTel(Integer.parseInt(TELEFONE.getText()));
           func.setUsuEndereco(ENDUsuario.getText());       
           func.setUsuNumero(Integer.parseInt(NumeroUsuario.getText()));
           func.setUsuNumero(Integer.parseInt(NumeroUsuario.getText()));
           func.setUsuCep(Integer.parseInt(CEPUsuario.getText()));
           func.setUsuCidade(CidadeUsuario.getText());
           func.setUsuBairro(BairroUsuario.getText());
           func.setUsuNascimento(Integer.parseInt(DATANASCIUsuario.getText()));
           func.setUsuSalario(Integer.parseInt(SalarioUsuario.getText()));
           
          
           control.Cadastra(func);
           
           jTextFieldNome.setText("");
           jTextFieldCargo.setText("");
           jTextFieldRG.setText("");
           jTextFieldSexo.setText("");
           jTextFieldCPF.setText("");
           CELULAR.setText("");
           TELEFONE.setText("");
           ENDUsuario.setText("");
           NumeroUsuario.setText("");
           CEPUsuario.setText("");
           CidadeUsuario.setText("");
           BairroUsuario.setText("");
           DATANASCIUsuario.setText("");
           SalarioUsuario.setText("");
          
           
           jTextFieldNome.setEnabled(false);
           jTextFieldCargo.setEnabled(false);
           jTextFieldRG.setEnabled(false);
           jTextFieldSexo.setEnabled(false);
           jTextFieldCPF.setEnabled(false);
           CELULAR.setEnabled(false);
           TELEFONE.setEnabled(false);
           ENDUsuario.setEnabled(false);
           NumeroUsuario.setEnabled(false);
           CEPUsuario.setEnabled(false);
           CidadeUsuario.setEnabled(false);
           BairroUsuario.setEnabled(false);
           DATANASCIUsuario.setEnabled(false);
           SalarioUsuario.setEnabled(false);
          
           jButtonSALVAR.setEnabled(false);
       preencherTabela("select * from usuario order by usu_nome");
    }//GEN-LAST:event_jButtonSALVARActionPerformed
    }
    private void jButtonSAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAIRActionPerformed
         this.dispose();
    }//GEN-LAST:event_jButtonSAIRActionPerformed

    private void jButtonPESQUISAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPESQUISAActionPerformed
       func.setPesquisaUser(jTextFieldPesquisa.getText());
    BeansUsuario model= control.buscaUsuario(func);
    jTextFieldNome.setText(model.getUsuNome());
    jTextFieldCargo.setText(model.getUsuProfissao());
    IDcodigo.setText(String.valueOf(model.getUsuCod()));
    jTextFieldCPF.setText(String.valueOf(model.getUsuCpf()));
    jTextFieldSexo.setText(model.getUsuSexo());
    jTextFieldRG.setText(String.valueOf(model.getUsuRg()));
    TELEFONE.setText(String.valueOf(model.getUsuTel()));
    CELULAR.setText(String.valueOf(model.getUsuCel()));
    ENDUsuario.setText(model.getUsuEndereco());
    NumeroUsuario.setText(String.valueOf(model.getUsuNumero()));
    CEPUsuario.setText(String.valueOf(model.getUsuCep()));
    CidadeUsuario.setText(model.getUsuCidade());
    BairroUsuario.setText(model.getUsuBairro());
    DATANASCIUsuario.setText(String.valueOf(model.getUsuNascimento()));
    SalarioUsuario.setText(String.valueOf(model.getUsuSalario()));
    jButtonNOVO.setEnabled(false);
    
     jTextFieldNome.setText("");
          IDcodigo.setText("");
        jTextFieldCargo.setText("");
        jTextFieldCPF.setText("");
        jTextFieldRG.setText("");
        jTextFieldSexo.setText("");
        TELEFONE.setText("");
        CELULAR.setText("");
        ENDUsuario.setText("");
        NumeroUsuario.setText("");
        CEPUsuario.setText("");
        CidadeUsuario.setText("");
        BairroUsuario.setText("");
        DATANASCIUsuario.setText("");
        SalarioUsuario .setText("");       
    preencherTabela("select * from usuario where usu_nome like'%"+func.getPesquisaUser()+"%'");
    }//GEN-LAST:event_jButtonPESQUISAActionPerformed

    private void jButtonCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCANCELARActionPerformed
       jTextFieldNome.setEnabled(!true);
        jTextFieldCargo.setEnabled(!true);
        jTextFieldCPF.setEnabled(!true);
        jTextFieldRG.setEnabled(!true);
        jTextFieldSexo.setEnabled(!true);
        TELEFONE.setEnabled(!true);
        CELULAR.setEnabled(!true);
        ENDUsuario.setEnabled(!true);
           NumeroUsuario.setEnabled(!true);
           CEPUsuario.setEnabled(!true);
           CidadeUsuario.setEnabled(!true);
           BairroUsuario.setEnabled(!true);
           DATANASCIUsuario.setEnabled(!true);
           SalarioUsuario.setEnabled(!true);
      
        jButtonSALVAR.setEnabled(!true);
        jButtonCANCELAR.setEnabled(!true);
        
        jButtonNOVO.setEnabled(true);
        jButtonEDITAR.setEnabled(false);
        jButtonEXCLUIR.setEnabled(false);
        jTextFieldPesquisa.setEnabled(true);
        jButtonPESQUISA.setEnabled(true);
        
        jTextFieldNome.setText("");
          IDcodigo.setText("");
        jTextFieldCargo.setText("");
        jTextFieldCPF.setText("");
        jTextFieldRG.setText("");
        jTextFieldSexo.setText("");
        TELEFONE.setText("");
        CELULAR.setText("");
        ENDUsuario.setText("");
        NumeroUsuario.setText("");
        CEPUsuario.setText("");
        CidadeUsuario.setText("");
        BairroUsuario.setText("");
        DATANASCIUsuario.setText("");
        SalarioUsuario .setText("");
        
    }//GEN-LAST:event_jButtonCANCELARActionPerformed

    private void jButtonEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEDITARActionPerformed
          flag=2; 
        jTextFieldNome.setEnabled(true);
        jTextFieldCargo.setEnabled(true);
        jTextFieldCPF.setEnabled(true);
        jTextFieldRG.setEnabled(true);
        jTextFieldSexo.setEnabled(true);
        TELEFONE.setEnabled(true);
        CELULAR.setEnabled(true);
        ENDUsuario.setEnabled(true);
           NumeroUsuario.setEnabled(true);
           CEPUsuario.setEnabled(true);
           CidadeUsuario.setEnabled(true);
           BairroUsuario.setEnabled(true);
           DATANASCIUsuario.setEnabled(true);
           SalarioUsuario.setEnabled(true);
           
            jButtonSALVAR.setEnabled(true);
        jButtonCANCELAR.setEnabled(true);
        jButtonEDITAR.setEnabled(false);
        jButtonNOVO.setEnabled(false);
        jButtonEXCLUIR.setEnabled(false);
    }//GEN-LAST:event_jButtonEDITARActionPerformed

    private void jTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMouseClicked
        String usu_nome= ""+jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(),1);
       conecta.Conexao();
       conecta.executaSql("select * from usuario where usu_nome='"+usu_nome+"'");
     try {
         conecta.rs.first();
         IDcodigo.setText(String.valueOf(conecta.rs.getInt("usu_cod")));
         jTextFieldNome.setText(conecta.rs.getString("usu_nome"));
         jTextFieldCargo.setText(conecta.rs.getString("usu_profissao"));
         jTextFieldRG.setText(String.valueOf(conecta.rs.getInt("usu_rg")));
         jTextFieldSexo.setText(String.valueOf(conecta.rs.getInt("usu_sexo")));
         jTextFieldCPF.setText(conecta.rs.getString("usu_cpf"));
         CELULAR.setText(String.valueOf(conecta.rs.getInt("usu_cel")));
        TELEFONE.setText(String.valueOf(conecta.rs.getInt("usu_tel")));
        
        ENDUsuario.setText(String.valueOf(conecta.rs.getInt("usu_endereco")));
        NumeroUsuario.setText(String.valueOf(conecta.rs.getInt("usu_numero")));
        CEPUsuario.setText(String.valueOf(conecta.rs.getInt("usu_cep")));
        CidadeUsuario.setText(String.valueOf(conecta.rs.getInt("usu_cidade")));
        BairroUsuario.setText(String.valueOf(conecta.rs.getInt("usu_bairro")));
        DATANASCIUsuario.setText(String.valueOf(conecta.rs.getInt("usu_nascimento")));
        SalarioUsuario.setText(String.valueOf(conecta.rs.getInt("usu_salario")));

         
     } catch (SQLException ex) {
        //JOptionPane.showMessageDialog(rootPane,"Erro ao Selecionar os dados"+ex);     }
       conecta.desconecta();
       jButtonEDITAR.setEnabled(true);
       jButtonEXCLUIR.setEnabled(true);
     } 
    }//GEN-LAST:event_jTableUsuarioMouseClicked
public void preencherTabela(String sql){
       ArrayList dados  = new ArrayList();
       String [] colunas = new String[]{"ID","nome","Profissao","CPF","sexo","TEL","CEL","RG"};
       conecta.Conexao();
       conecta.executaSql(sql);
       
       
       try{
           conecta.rs.first();
           do{
               dados.add(new Object[]{conecta.rs.getString("usu_cod"),conecta.rs.getString("usu_nome"),conecta.rs.getString("usu_profissao"),
                   conecta.rs.getString("usu_cpf"),conecta.rs.getString("usu_sexo"),
                   conecta.rs.getString("usu_tel"),conecta.rs.getString("usu_cel"),conecta.rs.getString("usu_rg")});
           }while(conecta.rs.next());
           
       }catch (SQLException ex){
          // JOptionPane.showMessageDialog(rootPane,"Erro ao Preencher ArrayList"+ex);
           
       }
       ModeloTabela modelo = new ModeloTabela(dados,colunas);
       jTableUsuario.setModel(modelo);
       jTableUsuario.getColumnModel().getColumn(0).setPreferredWidth(35);
       jTableUsuario.getColumnModel().getColumn(0).setResizable(false);
       jTableUsuario.getColumnModel().getColumn(1).setPreferredWidth(180);
       jTableUsuario.getColumnModel().getColumn(1).setResizable(false);
       jTableUsuario.getColumnModel().getColumn(2).setPreferredWidth(80);
       jTableUsuario.getColumnModel().getColumn(2).setResizable(false);
       jTableUsuario.getColumnModel().getColumn(3).setPreferredWidth(80);
       jTableUsuario.getColumnModel().getColumn(3).setResizable(false);
        jTableUsuario.getColumnModel().getColumn(4).setPreferredWidth(80);
       jTableUsuario.getColumnModel().getColumn(4).setResizable(false);
        jTableUsuario.getColumnModel().getColumn(5).setPreferredWidth(80);
       jTableUsuario.getColumnModel().getColumn(5).setResizable(false);
        jTableUsuario.getColumnModel().getColumn(6).setPreferredWidth(80);
       jTableUsuario.getColumnModel().getColumn(6).setResizable(false);
        jTableUsuario.getColumnModel().getColumn(7).setPreferredWidth(80);
       jTableUsuario.getColumnModel().getColumn(7).setResizable(false);
       jTableUsuario.getTableHeader().setReorderingAllowed(false);
       jTableUsuario.setAutoResizeMode(jTableUsuario.AUTO_RESIZE_OFF);
       jTableUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
       conecta.desconecta();
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroUsuario;
    private javax.swing.JTextField CELULAR;
    private javax.swing.JTextField CEPUsuario;
    private javax.swing.JTextField CidadeUsuario;
    private javax.swing.JTextField DATANASCIUsuario;
    private javax.swing.JTextField ENDUsuario;
    private javax.swing.JTextField IDcodigo;
    private javax.swing.JLabel NOMEFUNC;
    private javax.swing.JTextField NumeroUsuario;
    private javax.swing.JTextField SalarioUsuario;
    private javax.swing.JTextField TELEFONE;
    private javax.swing.JLabel codFunc;
    private javax.swing.JButton jButtonCANCELAR;
    private javax.swing.JButton jButtonEDITAR;
    private javax.swing.JButton jButtonEXCLUIR;
    private javax.swing.JButton jButtonNOVO;
    private javax.swing.JButton jButtonPESQUISA;
    private javax.swing.JButton jButtonSAIR;
    private javax.swing.JButton jButtonSALVAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldSexo;
    // End of variables declaration//GEN-END:variables
}
