/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import ModeloBeans.BeansFuncionario;
import ModeloConection.ConectaDB;
import ModeloDao.DaoFuncionario;
import ModeloDao.ModeloTabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Bruno
 */
public class FormFuncionario extends javax.swing.JFrame {
 BeansFuncionario func = new BeansFuncionario();
 DaoFuncionario control = new DaoFuncionario();
 ConectaDB conecta= new ConectaDB();
 int flag=0;
  
    public FormFuncionario() {
        initComponents();
        preencherTabela("select * from funcionario order by nome_funcionario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeFuncionario = new javax.swing.JLabel();
        cargo = new javax.swing.JLabel();
        CPF = new javax.swing.JLabel();
        RG = new javax.swing.JLabel();
        SEXO = new javax.swing.JLabel();
        sexoFuncionario = new javax.swing.JTextField();
        RGFuncionario = new javax.swing.JTextField();
        CPFFuncionario = new javax.swing.JTextField();
        MatriculaFuncionario = new javax.swing.JTextField();
        cargoFuncionario = new javax.swing.JTextField();
        NomeCompletoFuncionario = new javax.swing.JTextField();
        TEL = new javax.swing.JLabel();
        TELFuncionario = new javax.swing.JTextField();
        CEL = new javax.swing.JLabel();
        CELFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loginFuncionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        senhaFuncionario = new javax.swing.JPasswordField();
        cadastrarBtn = new javax.swing.JButton();
        BOTAONOVO = new javax.swing.JButton();
        BOTAOEDITAR = new javax.swing.JButton();
        BOTAOEXCLUIR = new javax.swing.JButton();
        BOTAOPESQUISA = new javax.swing.JButton();
        CAMPOPESQUISA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCadastro = new javax.swing.JTable();
        jButtonCancelar = new javax.swing.JButton();
        TEXTOid = new javax.swing.JLabel();
        jButtonSAIR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        nomeFuncionario.setText("Nome Completo:");

        cargo.setText("Cargo:");

        CPF.setText("CPF:");

        RG.setText("RG:");

        SEXO.setText("SEXO:");

        sexoFuncionario.setEnabled(false);
        sexoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoFuncionarioActionPerformed(evt);
            }
        });

        RGFuncionario.setEnabled(false);
        RGFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGFuncionarioActionPerformed(evt);
            }
        });

        CPFFuncionario.setEnabled(false);
        CPFFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFFuncionarioActionPerformed(evt);
            }
        });

        MatriculaFuncionario.setEnabled(false);
        MatriculaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaFuncionarioActionPerformed(evt);
            }
        });

        cargoFuncionario.setEnabled(false);
        cargoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoFuncionarioActionPerformed(evt);
            }
        });

        NomeCompletoFuncionario.setEnabled(false);
        NomeCompletoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCompletoFuncionarioActionPerformed(evt);
            }
        });

        TEL.setText("TEL:");

        TELFuncionario.setEnabled(false);

        CEL.setText("CEL:");

        CELFuncionario.setEnabled(false);
        CELFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CELFuncionarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Login:");

        loginFuncionario.setEnabled(false);
        loginFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFuncionarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Senha:");

        senhaFuncionario.setEnabled(false);

        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.setEnabled(false);
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        BOTAONOVO.setText("NOVO");
        BOTAONOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAONOVOActionPerformed(evt);
            }
        });

        BOTAOEDITAR.setText("EDITAR");
        BOTAOEDITAR.setEnabled(false);
        BOTAOEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOEDITARActionPerformed(evt);
            }
        });

        BOTAOEXCLUIR.setText("EXCLUIR");
        BOTAOEXCLUIR.setEnabled(false);
        BOTAOEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOEXCLUIRActionPerformed(evt);
            }
        });

        BOTAOPESQUISA.setText("PESQUISA");
        BOTAOPESQUISA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOPESQUISAActionPerformed(evt);
            }
        });

        TabelaCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCadastroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaCadastro);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        TEXTOid.setText("ID:");

        jButtonSAIR.setText("SAIR");
        jButtonSAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TEXTOid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SEXO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NomeCompletoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sexoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(RG, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RGFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CPFFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CAMPOPESQUISA, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BOTAOPESQUISA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(TEL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TELFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(CEL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CELFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(loginFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(senhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(530, 530, 530))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BOTAONOVO, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cadastrarBtn))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(BOTAOEDITAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BOTAOEXCLUIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(jButtonSAIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(376, 376, 376))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEXTOid)
                    .addComponent(MatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(BOTAONOVO)
                        .addGap(18, 18, 18)
                        .addComponent(cadastrarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BOTAOEXCLUIR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BOTAOEDITAR)
                        .addGap(0, 0, 0)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSAIR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NomeCompletoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TEL)
                                .addComponent(TELFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CELFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CEL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CPFFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RGFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sexoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RG, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(SEXO, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(senhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BOTAOPESQUISA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CAMPOPESQUISA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro Funcionário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(972, 832));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sexoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoFuncionarioActionPerformed

    private void RGFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RGFuncionarioActionPerformed

    private void CPFFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFFuncionarioActionPerformed

    private void MatriculaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatriculaFuncionarioActionPerformed

    private void cargoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoFuncionarioActionPerformed

    private void NomeCompletoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCompletoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCompletoFuncionarioActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        if(NomeCompletoFuncionario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"preencher o nome para continuar");
           NomeCompletoFuncionario.requestFocus();
           
        }else if (senhaFuncionario.getText().isEmpty()){
       JOptionPane.showMessageDialog(null,"preencher o MATRICULA para continuar");
         senhaFuncionario.requestFocus();

        }else
        if (flag==1){
           func.setNome(NomeCompletoFuncionario.getText());
           func.setCargo(cargoFuncionario.getText());
           func.setSexo(sexoFuncionario.getText());
           func.setLogin(loginFuncionario.getText());
           func.setRG(Integer.parseInt(RGFuncionario.getText()));
           func.setCEL(Integer.parseInt(CELFuncionario.getText()));
           func.setCPF(Integer.parseInt(CPFFuncionario.getText()));
           func.setSenha(Integer.parseInt(senhaFuncionario.getText()));       
           func.setTEL(Integer.parseInt(TELFuncionario.getText()));
           control.Cadastra(func);
           NomeCompletoFuncionario.setText("");
           RGFuncionario.setText("");
           cargoFuncionario.setText("");
           sexoFuncionario.setText("");
           loginFuncionario.setText("");
           CELFuncionario.setText("");
           CPFFuncionario.setText("");
           senhaFuncionario.setText("");
           TELFuncionario.setText("");
           NomeCompletoFuncionario.setEnabled(false);
           RGFuncionario.setEnabled(false);
           MatriculaFuncionario.setEnabled(false);
           cargoFuncionario.setEnabled(false);
           sexoFuncionario.setEnabled(false);
           loginFuncionario.setEnabled(false);
           CELFuncionario.setEnabled(false);
           CPFFuncionario.setEnabled(false);
           senhaFuncionario.setEnabled(false);
           TELFuncionario.setEnabled(false);
           cadastrarBtn.setEnabled(false);
    preencherTabela("select * from funcionario order by nome_funcionario");

        }else{
           func.setNome(NomeCompletoFuncionario.getText());
           func.setCargo(cargoFuncionario.getText());
           func.setSexo(sexoFuncionario.getText());
           func.setLogin(loginFuncionario.getText());
           func.setRG(Integer.parseInt(RGFuncionario.getText()));
           func.setCEL(Integer.parseInt(CELFuncionario.getText()));
           func.setCPF(Integer.parseInt(CPFFuncionario.getText()));
           func.setSenha(Integer.parseInt(senhaFuncionario.getText()));
           func.setTEL(Integer.parseInt(TELFuncionario.getText()));
           control.Editar(func);
           NomeCompletoFuncionario.setText("");
           RGFuncionario.setText("");
           cargoFuncionario.setText("");
           sexoFuncionario.setText("");
           loginFuncionario.setText("");
           CELFuncionario.setText("");
           CPFFuncionario.setText("");
           senhaFuncionario.setText("");
           TELFuncionario.setText("");
           NomeCompletoFuncionario.setEnabled(false);
           RGFuncionario.setEnabled(false);
            MatriculaFuncionario.setEnabled(false);
           cargoFuncionario.setEnabled(false);
           sexoFuncionario.setEnabled(false);
           loginFuncionario.setEnabled(false);
           CELFuncionario.setEnabled(false);
           CPFFuncionario.setEnabled(false);
           senhaFuncionario.setEnabled(false);
           TELFuncionario.setEnabled(false);
           cadastrarBtn.setEnabled(false);
        preencherTabela("select * from funcionario order by nome_funcionario");

    }//GEN-LAST:event_cadastrarBtnActionPerformed
    }
    private void BOTAONOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAONOVOActionPerformed
        flag = 1 ;
        NomeCompletoFuncionario.setEnabled(true);
        cargoFuncionario.setEnabled(true);
        CPFFuncionario.setEnabled(true);
        RGFuncionario.setEnabled(true);
        sexoFuncionario.setEnabled(true);
        TELFuncionario.setEnabled(true);
        CELFuncionario.setEnabled(true);
        loginFuncionario.setEnabled(true);
        senhaFuncionario.setEnabled(true);
        cadastrarBtn.setEnabled(true);
        jButtonCancelar.setEnabled(true);
          NomeCompletoFuncionario.setText("");
          MatriculaFuncionario.setText("");
        cargoFuncionario.setText("");
        CPFFuncionario.setText("");
        RGFuncionario.setText("");
        sexoFuncionario.setText("");
        TELFuncionario.setText("");
        CELFuncionario.setText("");
        loginFuncionario.setText("");
        senhaFuncionario.setText("");
        BOTAOEDITAR.setEnabled(false);
        BOTAOEXCLUIR.setEnabled(false);
        BOTAOPESQUISA.setEnabled(false);
        CAMPOPESQUISA.setEnabled(false);
       
        
    }//GEN-LAST:event_BOTAONOVOActionPerformed

    private void BOTAOPESQUISAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOPESQUISAActionPerformed
    func.setPesquisa(CAMPOPESQUISA.getText());
    BeansFuncionario model= control.buscaFuncionario(func);
    NomeCompletoFuncionario.setText(model.getNome());
    cargoFuncionario.setText(model.getCargo());
    MatriculaFuncionario.setText(String.valueOf(model.getMatricula()));
    CPFFuncionario.setText(String.valueOf(model.getCPF()));
    sexoFuncionario.setText(model.getSexo());
    RGFuncionario.setText(String.valueOf(model.getRG()));
    TELFuncionario.setText(String.valueOf(model.getTEL()));
    CELFuncionario.setText(String.valueOf(model.getCEL()));
    loginFuncionario.setText(model.getLogin());
    senhaFuncionario.setText(String.valueOf(model.getSenha()));
    BOTAONOVO.setEnabled(false);
     NomeCompletoFuncionario.setText("");
          MatriculaFuncionario.setText("");
        cargoFuncionario.setText("");
        CPFFuncionario.setText("");
        RGFuncionario.setText("");
        sexoFuncionario.setText("");
        TELFuncionario.setText("");
        CELFuncionario.setText("");
        loginFuncionario.setText("");
        senhaFuncionario.setText("");
    preencherTabela("select * from funcionario where nome_funcionario like'%"+func.getPesquisa()+"%'");
    
    
    }//GEN-LAST:event_BOTAOPESQUISAActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        NomeCompletoFuncionario.setEnabled(!true);
        cargoFuncionario.setEnabled(!true);
        CPFFuncionario.setEnabled(!true);
        RGFuncionario.setEnabled(!true);
        sexoFuncionario.setEnabled(!true);
        TELFuncionario.setEnabled(!true);
        CELFuncionario.setEnabled(!true);
        loginFuncionario.setEnabled(!true);
        senhaFuncionario.setEnabled(!true);
        cadastrarBtn.setEnabled(!true);
        jButtonCancelar.setEnabled(!true);
        BOTAONOVO.setEnabled(true);
        BOTAOEDITAR.setEnabled(false);
        BOTAOEXCLUIR.setEnabled(false);
        CAMPOPESQUISA.setEnabled(true);
        BOTAOPESQUISA.setEnabled(true);
         NomeCompletoFuncionario.setText("");
         MatriculaFuncionario.setText("");
        cargoFuncionario.setText("");
        CPFFuncionario.setText("");
        RGFuncionario.setText("");
        sexoFuncionario.setText("");
        TELFuncionario.setText("");
        CELFuncionario.setText("");
        loginFuncionario.setText("");
        senhaFuncionario.setText("");
        
        
        
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void BOTAOEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOEDITARActionPerformed
        flag=2;  
        NomeCompletoFuncionario.setEnabled(true);
        cargoFuncionario.setEnabled(true);
        CPFFuncionario.setEnabled(true);
        RGFuncionario.setEnabled(true);
        sexoFuncionario.setEnabled(true);
        TELFuncionario.setEnabled(true);
        CELFuncionario.setEnabled(true);
        loginFuncionario.setEnabled(true);
        senhaFuncionario.setEnabled(true);
        cadastrarBtn.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        BOTAOEDITAR.setEnabled(false);
        BOTAONOVO.setEnabled(false);
        BOTAOEXCLUIR.setEnabled(false);
        
        
    }//GEN-LAST:event_BOTAOEDITARActionPerformed

    private void BOTAOEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOEXCLUIRActionPerformed
        int resposta= 0;
        resposta =JOptionPane.showConfirmDialog(rootPane,"Deseja Realmente Excluir?");
        if(resposta ==JOptionPane.YES_OPTION){
            func.setMatricula(Integer.parseInt(MatriculaFuncionario.getText()));
            control.Excluir(func);
           NomeCompletoFuncionario.setText("");
           RGFuncionario.setText("");
           cargoFuncionario.setText("");
           sexoFuncionario.setText("");
           loginFuncionario.setText("");
           CELFuncionario.setText("");
           CPFFuncionario.setText("");
           senhaFuncionario.setText("");
           TELFuncionario.setText("");
           NomeCompletoFuncionario.setEnabled(false);
            MatriculaFuncionario.setEnabled(false);
            RGFuncionario.setEnabled(false);
           cargoFuncionario.setEnabled(false);
           sexoFuncionario.setEnabled(false);
           loginFuncionario.setEnabled(false);
           CELFuncionario.setEnabled(false);
           CPFFuncionario.setEnabled(false);
           senhaFuncionario.setEnabled(false);
           TELFuncionario.setEnabled(false);
           cadastrarBtn.setEnabled(false);
           BOTAOEDITAR.setEnabled(false);
 preencherTabela("select * from funcionario order by nome_funcionario");

        }
    }//GEN-LAST:event_BOTAOEXCLUIRActionPerformed

    private void CELFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CELFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CELFuncionarioActionPerformed

    private void loginFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFuncionarioActionPerformed

    private void jButtonSAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAIRActionPerformed
            this.dispose();
    }//GEN-LAST:event_jButtonSAIRActionPerformed

    private void TabelaCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCadastroMouseClicked
       String nome_funcionario= ""+TabelaCadastro.getValueAt(TabelaCadastro.getSelectedRow(),1);
       conecta.Conexao();
       conecta.executaSql("select * from funcionario where nome_funcionario='"+nome_funcionario+"'");
     try {
         conecta.rs.first();
         MatriculaFuncionario.setText(String.valueOf(conecta.rs.getInt("matricula_funcionario")));
         NomeCompletoFuncionario.setText(conecta.rs.getString("nome_funcionario"));
         cargoFuncionario.setText(conecta.rs.getString("cargo_funcionario"));
         CPFFuncionario.setText(String.valueOf(conecta.rs.getInt("cpf_funcionario")));
         RGFuncionario.setText(String.valueOf(conecta.rs.getInt("rg_funcionario")));
         sexoFuncionario.setText(conecta.rs.getString("sexo_funcionario"));
         TELFuncionario.setText(String.valueOf(conecta.rs.getInt("tel_funcionario")));
        CELFuncionario.setText(String.valueOf(conecta.rs.getInt("cel_funcionario")));

         
     } catch (SQLException ex) {
     //   JOptionPane.showMessageDialog(rootPane,"Erro ao Selecionar os dados"+ex);     }
       conecta.desconecta();
       BOTAOEDITAR.setEnabled(true);
       BOTAOEXCLUIR.setEnabled(true);
     }
    }//GEN-LAST:event_TabelaCadastroMouseClicked

   public void preencherTabela(String sql){
       ArrayList dados  = new ArrayList();
       String [] colunas = new String[]{"ID","nome","cargo","CPF","sexo","TEL","CEL","RG"};
       conecta.Conexao();
       conecta.executaSql(sql);
       
       
       try{
           conecta.rs.first();
           do{
               dados.add(new Object[]{conecta.rs.getString("matricula_funcionario"),conecta.rs.getString("nome_funcionario"),conecta.rs.getString("cargo_funcionario"),
                   conecta.rs.getString("cpf_funcionario"),conecta.rs.getString("sexo_funcionario"),
                   conecta.rs.getString("tel_funcionario"),conecta.rs.getString("cel_funcionario"),conecta.rs.getString("rg_funcionario")});
           }while(conecta.rs.next());
           
       }catch (SQLException ex){
           JOptionPane.showMessageDialog(rootPane,"Erro ao Preencher ArrayList"+ex);
           
       }
       ModeloTabela modelo = new ModeloTabela(dados,colunas);
       TabelaCadastro.setModel(modelo);
       TabelaCadastro.getColumnModel().getColumn(0).setPreferredWidth(35);
       TabelaCadastro.getColumnModel().getColumn(0).setResizable(false);
       TabelaCadastro.getColumnModel().getColumn(1).setPreferredWidth(180);
       TabelaCadastro.getColumnModel().getColumn(1).setResizable(false);
       TabelaCadastro.getColumnModel().getColumn(2).setPreferredWidth(80);
       TabelaCadastro.getColumnModel().getColumn(2).setResizable(false);
       TabelaCadastro.getColumnModel().getColumn(3).setPreferredWidth(80);
       TabelaCadastro.getColumnModel().getColumn(3).setResizable(false);
        TabelaCadastro.getColumnModel().getColumn(4).setPreferredWidth(80);
       TabelaCadastro.getColumnModel().getColumn(4).setResizable(false);
        TabelaCadastro.getColumnModel().getColumn(5).setPreferredWidth(80);
       TabelaCadastro.getColumnModel().getColumn(5).setResizable(false);
        TabelaCadastro.getColumnModel().getColumn(6).setPreferredWidth(80);
       TabelaCadastro.getColumnModel().getColumn(6).setResizable(false);
        TabelaCadastro.getColumnModel().getColumn(7).setPreferredWidth(80);
       TabelaCadastro.getColumnModel().getColumn(7).setResizable(false);
       TabelaCadastro.getTableHeader().setReorderingAllowed(false);
       TabelaCadastro.setAutoResizeMode(TabelaCadastro.AUTO_RESIZE_OFF);
       TabelaCadastro.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
       conecta.desconecta();
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAOEDITAR;
    private javax.swing.JButton BOTAOEXCLUIR;
    private javax.swing.JButton BOTAONOVO;
    private javax.swing.JButton BOTAOPESQUISA;
    private javax.swing.JTextField CAMPOPESQUISA;
    private javax.swing.JLabel CEL;
    private javax.swing.JTextField CELFuncionario;
    private javax.swing.JLabel CPF;
    private javax.swing.JTextField CPFFuncionario;
    private javax.swing.JTextField MatriculaFuncionario;
    private javax.swing.JTextField NomeCompletoFuncionario;
    private javax.swing.JLabel RG;
    private javax.swing.JTextField RGFuncionario;
    private javax.swing.JLabel SEXO;
    private javax.swing.JLabel TEL;
    private javax.swing.JTextField TELFuncionario;
    private javax.swing.JLabel TEXTOid;
    private javax.swing.JTable TabelaCadastro;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JLabel cargo;
    private javax.swing.JTextField cargoFuncionario;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSAIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loginFuncionario;
    private javax.swing.JLabel nomeFuncionario;
    private javax.swing.JPasswordField senhaFuncionario;
    private javax.swing.JTextField sexoFuncionario;
    // End of variables declaration//GEN-END:variables
}
