package VIEW;

import ModeloConection.ConectaDB;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jgabr
 */

public class TelaMenu extends javax.swing.JFrame {
ConectaDB conecta= new ConectaDB();

    /**
     * Creates new form NewJFrame
     */
    public TelaMenu() {
        initComponents();
      conecta.Conexao();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInterno = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonFuncionario = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jButtonCarros = new javax.swing.JButton();
        TelaFundoInterno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTITULO = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonSAIR = new javax.swing.JButton();
        jLabelFUNDO = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        cadastros_menu = new javax.swing.JMenu();
        jMenuFuncionario = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuVeiculos = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        MENUSAIR = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        jMenu3.setText("jMenu3");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem Vindo");
        jInternalFrameBemVindo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInterno.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Cadastros:");
        jPanelInterno.add(jLabel2);
        jLabel2.setBounds(10, 30, 120, 30);

        jButtonFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/IMGFUNCIONARIO.png"))); // NOI18N
        jButtonFuncionario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionarioActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonFuncionario);
        jButtonFuncionario.setBounds(20, 70, 170, 200);

        jButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/Usuário-HM.png"))); // NOI18N
        jButtonClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonClientes);
        jButtonClientes.setBounds(200, 70, 270, 200);

        jButtonCarros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/carros.jpg"))); // NOI18N
        jButtonCarros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarrosActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonCarros);
        jButtonCarros.setBounds(480, 70, 329, 200);

        TelaFundoInterno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/TelaFundoInterno.jpg"))); // NOI18N
        jPanelInterno.add(TelaFundoInterno);
        TelaFundoInterno.setBounds(10, 0, 1300, 570);

        jInternalFrameBemVindo.getContentPane().add(jPanelInterno);
        jPanelInterno.setBounds(0, 30, 1290, 570);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de :");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 6, 270, 20);

        jLabelTITULO.setFont(new java.awt.Font("Vijaya", 1, 48)); // NOI18N
        jLabelTITULO.setForeground(new java.awt.Color(255, 255, 51));
        jLabelTITULO.setText("Java Car´s");
        jInternalFrameBemVindo.getContentPane().add(jLabelTITULO);
        jLabelTITULO.setBounds(450, -60, 190, 70);

        jButton2.setText("jButton2");
        jInternalFrameBemVindo.getContentPane().add(jButton2);
        jButton2.setBounds(1130, -30, 79, 25);

        jButtonSAIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/sair.jpg"))); // NOI18N
        jButtonSAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSAIRActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonSAIR);
        jButtonSAIR.setBounds(1160, 0, 40, 30);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(20, 30, 1220, 640);

        jLabelFUNDO.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelFUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/TelaFundoInterno.jpg"))); // NOI18N
        getContentPane().add(jLabelFUNDO);
        jLabelFUNDO.setBounds(-40, -160, 1480, 990);

        cadastros_menu.setText("Cadastros");

        jMenuFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuFuncionario.setText("Funcionário");
        jMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFuncionarioActionPerformed(evt);
            }
        });
        cadastros_menu.add(jMenuFuncionario);

        jMenuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuUsuario.setText("Cliente");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        cadastros_menu.add(jMenuUsuario);

        jMenuVeiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuVeiculos.setText("veiculos");
        jMenuVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVeiculosActionPerformed(evt);
            }
        });
        cadastros_menu.add(jMenuVeiculos);

        Menu.add(cadastros_menu);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela Bem Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBemVindo);

        Menu.add(jMenuFerramentas);

        MENUSAIR.setText("Sair");

        jMenuItem1.setText("sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MENUSAIR.add(jMenuItem1);

        Menu.add(MENUSAIR);

        setJMenuBar(Menu);

        setSize(new java.awt.Dimension(1256, 771));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFuncionarioActionPerformed
        FormFuncionario CadFuncionario = new FormFuncionario();
        CadFuncionario.setVisible(true);
 
    }//GEN-LAST:event_jMenuFuncionarioActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
     FormUser CadUsuario = new FormUser();
        CadUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVeiculosActionPerformed
       formCarros CadCarros = new  formCarros();
        CadCarros.setVisible(true);
    }//GEN-LAST:event_jMenuVeiculosActionPerformed

    private void jButtonSAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSAIRActionPerformed
   jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonSAIRActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
      TelaMenu jInternalFrameBemVindo = new TelaMenu();
        jInternalFrameBemVindo.setVisible(true);
     
     
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionarioActionPerformed
       FormFuncionario CadFuncionario = new FormFuncionario();
        CadFuncionario.setVisible(true);
    }//GEN-LAST:event_jButtonFuncionarioActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
     
         FormUser CadTipoMobilidade = new FormUser();
        CadTipoMobilidade.setVisible(true);
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarrosActionPerformed
            formCarros CadUsuario = new formCarros();
        CadUsuario.setVisible(true);
    }//GEN-LAST:event_jButtonCarrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */


        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MENUSAIR;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel TelaFundoInterno;
    private javax.swing.JMenu cadastros_menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCarros;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonFuncionario;
    private javax.swing.JButton jButtonSAIR;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFUNDO;
    private javax.swing.JLabel jLabelTITULO;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuFuncionario;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JMenuItem jMenuVeiculos;
    private javax.swing.JPanel jPanelInterno;
    // End of variables declaration//GEN-END:variables

    private static class CadastroVeilculos {

        public CadastroVeilculos() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
